### ISSUE TITLE
consider adding categorization of taxa into preferred habitat

### ISSUE THREAD

**Issue by jeanetteclark** [Delta-Stewardship-Council/deltafish#4]
From Ted at the estuarine ecology team meeting, consider categorizing the fish into general habitat associations like Mahardja et al. 2017, i.e. benthic, littoral, pelagic.

**Comment by sbashevkin** [comment]
I think this is an interesting idea, but maybe it's something the data-analyst should be doing rather than the data aggregator? If someone publishes a categorization of all our fish species into those categories it would be easy to pull that in, but I'm not sure we should be making that categorization.

**Comment by jeanetteclark** [comment]
closing this issue, I agree that this feature is out of scope
